# Push Proxy 服务配置

[services.push_proxy]
kafka = "push"
message_topic = "push-messages"
notification_topic = "push-notifications"
timeout_ms = 5000

[services.push_proxy.server]
address = "0.0.0.0"
port = 60071

